# Generated by Django 4.1.1 on 2023-03-28 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='filed_lawsuits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_filed', models.DateField()),
                ('court', models.CharField(max_length=255)),
                ('cnr', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('outcome', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('judges', models.ManyToManyField(blank=True, to='accounts.judge')),
                ('refference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clientcase')),
            ],
        ),
    ]
