# Generated by Django 4.1.1 on 2023-03-30 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_filed_lawsuits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filed_lawsuits',
            name='cnr',
        ),
        migrations.RemoveField(
            model_name='filed_lawsuits',
            name='court',
        ),
        migrations.RemoveField(
            model_name='filed_lawsuits',
            name='date_filed',
        ),
        migrations.RemoveField(
            model_name='filed_lawsuits',
            name='description',
        ),
        migrations.RemoveField(
            model_name='filed_lawsuits',
            name='judges',
        ),
        migrations.RemoveField(
            model_name='filed_lawsuits',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='filed_lawsuits',
            name='status',
        ),
        migrations.RemoveField(
            model_name='filed_lawsuits',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='filed_lawsuits',
            name='title',
        ),
    ]
