# Generated by Django 4.1.1 on 2023-03-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_filed_lawsuits_cnr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filed_lawsuits',
            name='cnr',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='filed_lawsuits',
            name='court',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='filed_lawsuits',
            name='date_filed',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='filed_lawsuits',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='filed_lawsuits',
            name='outcome',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='filed_lawsuits',
            name='status',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='filed_lawsuits',
            name='sub_title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='filed_lawsuits',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='judge',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
