# Generated by Django 4.1.1 on 2023-05-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_defendant_filed_lawsuits_defendants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='filed_lawsuits',
            name='court',
        ),
        migrations.AddField(
            model_name='filed_lawsuits',
            name='courts',
            field=models.ManyToManyField(blank=True, to='accounts.court'),
        ),
    ]
